Correction de la gestion des issues sur gitHub 18

diff --git a/.github/workflows/flutter-android.yml b/.github/workflows/flutter-android.yml
--- a/.github/workflows/flutter-android.yml
+++ b/.github/workflows/flutter-android.yml
@@ -61,28 +61,24 @@ jobs:
 
       - name: Run tests and generate JSON
         run: |
-          # Exécute les tests et écrit dans test_results.json
-          flutter test --machine test/tests/ > test/results/test_results.ndjson
-          # Récupère le code de sortie
-          TEST_EXIT_CODE=${PIPESTATUS[0]}
-          echo "Code de sortie des tests : $TEST_EXIT_CODE"
-          # Exporte la variable pour les étapes suivantes
-          echo "TEST_EXIT_CODE=$TEST_EXIT_CODE" >> $GITHUB_ENV
-        
-          
-
-      - name: Create GitHub issue if tests fail
-        run: |
-          echo "Création de l'issue GitHub pour tests échoués..."
+          flutter test --machine test/tests/ > test/results/test_results.ndjson   
           dart scripts/create_issue.dart
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        continue-on-error: true
 
-      - name: Stop workflow if tests failed
-        if: env.TEST_EXIT_CODE != '0'
-        run: |
-          echo "Tests échoués, arrêt du workflow."
-          exit 1
+      # - name: Create GitHub issue if tests fail
+      #   run: |
+      #     echo "Création de l'issue GitHub pour tests échoués..."
+      #     dart scripts/create_issue.dart
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      # - name: Stop workflow if tests failed
+      #   if: env.TEST_EXIT_CODE != '0'
+      #   run: |
+      #     echo "Tests échoués, arrêt du workflow."
+      #     exit 1
 
 
 
